kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: zimzua-db
spec:
  replicas:
  template:
    metadata:
      name: zimzua-db
      labels:
        app: zimzua
        role: db
    spec:
      containers:
      - name: zimzua-db
        image: 992189553983.dkr.ecr.ap-northeast-2.amazonaws.com/zimzua/db:0.3
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
