kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: zimzua-db
spec:
  replicas:
  template:
    metadata:
      name: zimzua-db
      labels:
        app: zimzua
        role: db
    spec:
      containers:
      - name: mysql
        image: zimzua-db
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
