kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: zimzua-api
spec:
  replicas: 1
  template:
    metadata:
      name: zimzua-api
      labels:
        app: zimzua
        role: api
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: zimzua-api
        image: 992189553983.dkr.ecr.ap-northeast-2.amazonaws.com/zimzua/api:0.4
        env:
        - name: DB_IP
          valueFrom:
            configMapKeyRef:
              name: zimzua-db-config
              key: db.ip
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: zimzua-db-config
              key: db.port
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: zimzua-db-config
              key: db.name
        - name: USER_NAME
          valueFrom:
            configMapKeyRef:
              name: zimzua-db-config
              key: username
        - name: USER_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: zimzua-db-config
              key: password
